name: Delete All Feature Databases

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type DELETE to confirm deletion of all feature namespaces'
        required: true
        type: string

jobs:
  delete_all:
    name: Delete All Feature Databases
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Confirm deletion
      run: |
        if [ "${{ inputs.confirm }}" != "DELETE" ]; then
          echo "❌ Confirmation failed. You must type DELETE to proceed."
          exit 1
        fi
    
    - name: Setup OCI CLI and Configure kubectl
      run: |
        bash -c "$(curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh)" -- --accept-all-defaults
        export PATH="$HOME/bin:$PATH"
        echo "$HOME/bin" >> $GITHUB_PATH
        mkdir -p ~/.oci
        echo "${{ secrets.OCI_KEY_FILE }}" > ~/.oci/key.pem
        chmod 600 ~/.oci/key.pem
        FINGERPRINT=$(openssl rsa -pubout -outform DER -in ~/.oci/key.pem 2>/dev/null | openssl md5 -c | awk -F'= ' '{print $2}')
        cat > ~/.oci/config << EOF
        [DEFAULT]
        user=${{ secrets.OCI_CLI_USER }}
        fingerprint=${FINGERPRINT}
        tenancy=${{ secrets.OCI_CLI_TENANCY }}
        region=${{ secrets.OCI_REGION }}
        key_file=$HOME/.oci/key.pem
        EOF
        chmod 600 ~/.oci/config
        mkdir -p ~/.kube
        $HOME/bin/oci ce cluster create-kubeconfig \
          --cluster-id ${{ secrets.OKE_CLUSTER_OCID }} \
          --file ~/.kube/config \
          --region '${{ secrets.OCI_REGION }}' \
          --token-version 2.0.0
    
    - name: Delete all feature namespaces
      run: |
        echo "=== Finding all feature namespaces ==="
        NAMESPACES=$(kubectl get namespaces -o name | grep 'namespace/feature-' | cut -d'/' -f2)
        
        if [ -z "$NAMESPACES" ]; then
          echo "No feature namespaces found"
          exit 0
        fi
        
        echo "Found namespaces:"
        echo "$NAMESPACES"
        echo ""
        
        for NS in $NAMESPACES; do
          echo "Deleting namespace: $NS"
          kubectl delete namespace "$NS" --wait=false
        done
        
        echo "✅ All feature namespaces deletion initiated"
